/** Generated by scripts/sync-office-sdk.mjs. */
export declare const OFFICE_SDK_VERSION = "1.0.0";
export declare const OFFICE_SDK_REVISION = "a1a5a0a5e313";
export declare const OFFICE_SDK_ROUTE_PREFIX = "/fylar-office-sdk";
export declare const OFFICE_SDK_BASE_PATH = "/fylar-office-sdk/1.0.0-a1a5a0a5e313";
//# sourceMappingURL=office-sdk.generated.d.ts.map