/** Generated by scripts/sync-office-sdk.mjs. */
export const OFFICE_SDK_VERSION = "1.0.0"
export const OFFICE_SDK_REVISION = "acd589284cb2"
export const OFFICE_SDK_ROUTE_PREFIX = '/fylar-office-sdk'
export const OFFICE_SDK_BASE_PATH = `${OFFICE_SDK_ROUTE_PREFIX}/${OFFICE_SDK_VERSION}-${OFFICE_SDK_REVISION}`
